runtime: python
env: flex
entrypoint: gunicorn -b :$PORT main:app

runtime_config:
  python_version: 3

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 300
  failure_threshold: 10
  success_threshold: 10
  app_start_timeout_sec: 1800